import { register } from 'node:module';
register(new URL('../src/jsx-loader.mjs', import.meta.url));
await import('../src/ui.js');
await import('../src/components.js');
await import('../src/agent.js');
await import('../src/tools.js');
await import('../src/cost.js');
await import('../src/paste.js');
await import('../src/clipboard.js');
await import('../src/gitinfo.js');
await import('../src/headless.js');
const { sanitize } = await import('../src/paste.js');
console.assert(sanitize('hi\x1b]52;c;Zm9v\x07there') === 'hithere', 'osc strip');
console.assert(sanitize('a\x1b[31mred\x1b[0m') === 'ared', 'csi strip');
console.assert(sanitize('a\x07b') === 'ab', 'bell strip');
console.assert(sanitize('line1\nline2\tok') === 'line1\nline2\tok', 'keep nl tab');
const { costUsd } = await import('../src/cost.js');
console.assert(costUsd({prompt_tokens:1000,completion_tokens:1000},'gpt-4o') > 0, 'cost');
console.assert(costUsd({prompt_tokens:1000,completion_tokens:1000},'unknown-9') === 0, 'unknown free');
const { toolDefs, summarizeToolResult } = await import('../src/tools.js');
console.assert(toolDefs(true).length === 8, '8 tools got ' + toolDefs(true).length);
console.assert(summarizeToolResult('grep','a.js:1:x\nb.js:2:y') === '2 行匹配', 'grep sum: '+summarizeToolResult('grep','a.js:1:x\nb.js:2:y'));
console.assert(summarizeToolResult('glob','a.js\nb.js') === '2 个文件', 'glob sum');
const { gitSummary } = await import('../src/gitinfo.js');
const g = gitSummary();
console.assert(g === null || typeof g.branch === 'string', 'gitSummary shape');
console.log('ALL CHECKS PASSED');
